STACK SEGMENT PARA STACK
	DB 64 DUP(' ')
STACK ENDS

DATA SEGMENT PARA 'DATA'

	BALL_X DW 0Ah ; POSICION EN X (COLUMNA) PARA LA PELOTA
	BALL_Y DW 0Ah ; POSICION EN Y (FILA) PARA LA PELOTA
	BALL_SIZE DW 04h ; TAMAÑO DE LA PELOTA 4X4 PIXELES 
	

DATA ENDS

CODE SEGMENT PARA 'CODE'

	MAIN PROC FAR
	ASSUME CS:CODE, DS:DATA, SS:STACK ; ESTABLECER LOS SEGMENTOS A SUS DEBIDOS REGISTROS (CS, DS, SS)
	PUSH DS 						  ; ENVIAR AL STACK EL SEGMENTO DE DATOS (REGISTRO DS)
	SUB AX, AX 						  ; LIMPIAR EL REGISTRO AX
	PUSH AX							  ; ENVIAR EL REGISTRO AX AL STACK
	MOV AX, DATA					  ; GUARDAR EL CONTENIDO DEL DATA SEGMENT EN EL REGISTRO AX
	MOV DS, AX						  ; GUARDAR EN EL REGISTRO DS EL CONTENIDO DEL REGISTRO AX
	POP AX							  ; GUARDAR EL TOP DEL STACK EN EL REGISTRO AX
	POP AX							  ; GUARDAR EL TOP DEL STACK EN EL REGISTRO AX


		MOV AH, 00h ; PONER LA CONFIGURACION HACIA VIDEO MODE
		MOV AL, 13h ; ELEGIR EL MODO DE VIDEO 
		INT 10h     ; EJECUTAR INT

        MOV AH, 0Bh ; ELEGIR COLOR DE FONDO
		MOV BH, 00h ; PALETA
        MOV BL, 00h ; ELEGIR COLOR (NEGRO)                   
        INT 10h     ; EJECUTAR INT                   

		CALL DRAW_BALL

		; Terminar programa
		;MOV AH, 4Ch
		;INT 21h

		RET
	MAIN ENDP

	DRAW_BALL PROC NEAR 
		
		MOV CX, BALL_X ; SELECCIONAR CORDENADA X (COLUMNA) INICIAL
		MOV DX, BALL_Y ; SELECCIONAR COORDENADA Y (FILA) INICIAL 
	
		DRAW_BALL_LABEL:

			MOV AH, 0Ch ; DIBUJAR UN PIXEL EN MODO GRAFICO
			MOV AL, 0Fh ; PONER DE COLOR BLANCO AL PIXEL
			MOV BH, 00h ; SELECCIONAR PAGINA DE VIDEO
			INT 10h 	; EJECUTAR INT
			INC CX 		; CX = CX + 1
			
			; CX - BALL_X > BALL_SIZE (Y -> IR A LA SIGUIENTE LINEA, N -> SEGUIAR A LA SIGUIENTE COLUMNA)
			MOV AX, CX
			SUB AX, BALL_X
			CMP AX, BALL_SIZE
			
			JNG DRAW_BALL_LABEL ; SALTAR SI NO ES MAYOR 

			MOV CX, BALL_X 			 ; PONER EL REGISTRO CX EN LA COLUMNA INICIAL
			INC DX					 ; AVANZAR UNA LINEA
			
			; DX - BALL_Y > BALL_SIZE (Y -> TERMINAR PROCEDIMIENTO, N -> SEGUIR A LA SIGUIENTE LINEA)
			MOV AX, DX
			SUB AX, BALL_Y
			CMP AX, BALL_SIZE
			JNG DRAW_BALL_LABEL


		RET
	DRAW_BALL ENDP

CODE ENDS
END