STACK SEGMENT PARA STACK
	DB 64 DUP(' ')
STACK ENDS

DATA SEGMENT PARA 'DATA'

	WINDOW_WIDTH  DW 140h 				; EL ANCHO DE LA VENTANA DE 320 PIXELES EN  HEXADECIMAL DADO POR EL VIDEO MODE
	WINDOW_HEIGHT DW 0C8h 				; EL ALTO DE LA VENTANA DE 200 PIXELES EN HEXADECIMAL  DADO POR EL VIDEO MODE
	WINDOW_BOUNDS DW 6					; VARIABLE USADA PARA LAS COLISIONES

	TIME_AUX DB 0 						; VARIABLE USADA PARA VERIFICAR SI EL TIEMPO HA CAMBIADO

	BALL_X 			DW 0A0h 			; POSICION EN X (COLUMNA) PARA LA PELOTA
	BALL_Y 			DW 64h 				; POSICION EN Y (FILA) PARA LA PELOTA
	BALL_SIZE 		DW 04h 				; TAMAÑO DE LA PELOTA 4X4 PIXELES 
	BALL_VELOCITY_X DW 05h 				; VELOCIDAD EN X (HORIZONTAL) DE LA PELOTA
	BALL_VELOCITY_Y DW 02h				; VELOCIDAD EN Y (VERTICAL) DE LA PELOTA

	BALL_ORIGINAL_POS_X DW 0A0h			; POSICION DE LA PELOTA EN X (HORIZONTAL), CENTRO HORIZONTAL DE LA PANTALLA 160 EN HEXADECIMAL 
	BALL_ORIGINAL_POS_Y DW 64h			; POSICION DE LA PELOTA EN Y (VERTICAL), CENTRO VERTICAL DE LA PANTALLA 100 EN HEXADECIMAL

DATA ENDS

CODE SEGMENT PARA 'CODE'

	MAIN PROC FAR
	ASSUME CS:CODE, DS:DATA, SS:STACK ; ESTABLECER LOS SEGMENTOS A SUS DEBIDOS REGISTROS (CS, DS, SS)
	PUSH DS 						  ; ENVIAR AL STACK EL SEGMENTO DE DATOS (REGISTRO DS)
	SUB AX, AX 						  ; LIMPIAR EL REGISTRO AX
	PUSH AX							  ; ENVIAR EL REGISTRO AX AL STACK
	MOV AX, DATA					  ; GUARDAR EL CONTENIDO DEL DATA SEGMENT EN EL REGISTRO AX
	MOV DS, AX						  ; GUARDAR EN EL REGISTRO DS EL CONTENIDO DEL REGISTRO AX
	POP AX							  ; GUARDAR EL TOP DEL STACK EN EL REGISTRO AX
	POP AX							  ; GUARDAR EL TOP DEL STACK EN EL REGISTRO AX


		MOV AH, 00h  	 ; PONER LA CONFIGURACION HACIA VIDEO MODE
		MOV AL, 13h  	 ; ELEGIR EL MODO DE VIDEO 
		INT 10h      	 ; EJECUTAR INT

        MOV AH, 0Bh  	 ; ELEGIR COLOR DE FONDO
		MOV BH, 00h  	 ; PALETA
        MOV BL, 00h  	 ; ELEGIR COLOR (NEGRO)                   
        INT 10h      	 ; EJECUTAR INT                   

		CHECK_TIME:
			MOV AH, 2Ch 	 ; OBTENER EL TIEMPO DEL SISTEMA
			INT 21h 	 	 ; CH = HORA, CL = MINUTO, DH = SEGUNDO, DL = 1/100 SEGUNDO
		
			; VERIFICAR SI EL TIEMPO ACTUAL ES IGUAL AL ANTERIOR (TIME_AUX)
			CMP DL, TIME_AUX 
		
			JE CHECK_TIME 	 ; SI ES IGUAL COMPARA OTRA VEZ SINO REALIZAR EL RESTO DE ACCIONES
			MOV TIME_AUX, DL
			
			CALL CLEAR_SCREEN

			CALL MOVE_BALL

			CALL DRAW_BALL

			JMP CHECK_TIME 	; LUEGO DE REALIZAR LAS ACCIONES VOLVER A REVISAR EL TIEMPO		

		; Terminar programa
		;MOV AH, 4Ch
		;INT 21h

		RET
	MAIN ENDP

	DRAW_BALL PROC NEAR 
		
		MOV CX, BALL_X ; SELECCIONAR CORDENADA X (COLUMNA) INICIAL
		MOV DX, BALL_Y ; SELECCIONAR COORDENADA Y (FILA) INICIAL 
	
		DRAW_BALL_LABEL:

			MOV AH, 0Ch 			; DIBUJAR UN PIXEL EN MODO GRAFICO
			MOV AL, 0Fh 			; PONER DE COLOR BLANCO AL PIXEL
			MOV BH, 00h 			; SELECCIONAR PAGINA DE VIDEO
			INT 10h 				; EJECUTAR INT
			INC CX 					; CX = CX + 1
			
			; CX - BALL_X > BALL_SIZE (Y -> IR A LA SIGUIENTE LINEA, N -> SEGUIAR A LA SIGUIENTE COLUMNA)
			MOV AX, CX
			SUB AX, BALL_X
			CMP AX, BALL_SIZE
			
			JNG DRAW_BALL_LABEL 	; SALTAR SI NO ES MAYOR 

			MOV CX, BALL_X 			; PONER EL REGISTRO CX EN LA COLUMNA INICIAL
			INC DX					; AVANZAR UNA LINEA
			
			; DX - BALL_Y > BALL_SIZE (Y -> TERMINAR PROCEDIMIENTO, N -> SEGUIR A LA SIGUIENTE LINEA)
			MOV AX, DX
			SUB AX, BALL_Y
			CMP AX, BALL_SIZE
			JNG DRAW_BALL_LABEL

		RET
	DRAW_BALL ENDP

	MOVE_BALL PROC NEAR

		; MUEVE HACIA EL REGISTRO AX LOS VALORES DE VELOCIDAD Y LOS AÑADE A LA POSICION DE DIBUJO

		MOV AX, BALL_VELOCITY_X 	; MOVER LA PELOTA HORIZONTALMENTE
		ADD BALL_X, AX
		
		MOV AX, WINDOW_BOUNDS 
		CMP BALL_X, AX	 			; BALL_X < WINDOW_BOUNDS (Y -> COLISIONO)
		JL RESET_BALL_POSITION			

		MOV AX, WINDOW_WIDTH
		SUB AX, BALL_SIZE
		SUB AX, WINDOW_BOUNDS
		CMP BALL_X, AX				; BALL_X > WINDOW_WIDTH - BALL_SIZE - WINDOW_BOUNDS (Y -> COLISIONO)
		JG RESET_BALL_POSITION

		MOV AX, BALL_VELOCITY_Y		; MOVER LA PELOTA VERTICALMENTE
		ADD BALL_Y, AX
		
		MOV AX, WINDOW_BOUNDS
		CMP BALL_Y, AX				; BALL_Y < WINDOW_BOUNDS (Y -> COLISIONO)
		JL RESET_BALL_POSITION

		MOV AX, WINDOW_HEIGHT
		SUB AX, BALL_SIZE
		SUB AX, WINDOW_BOUNDS
		CMP BALL_Y, AX
		JG RESET_BALL_POSITION		; BALL_Y > WINDOW_HEIGHT - BALL_SIZE - WINDOW_BOUNDS (Y -> COLISIONO)
		
		RET

		RESET_POSITION:
			CALL RESET_BALL_POSITION
			RET

	MOVE_BALL ENDP

	RESET_BALL_POSITION PROC NEAR

		MOV AX, BALL_ORIGINAL_POS_X
		MOV BALL_X, AX

		MOV AX, BALL_ORIGINAL_POS_Y
		MOV BALL_Y, AX

		RET
	RESET_BALL_POSITION ENDP


	CLEAR_SCREEN PROC NEAR
		; EXPLICACION DETALLADA EN EL DOCUMENTO DE CLEAR_SCREEN.MD
		MOV AX, 0A000h   ; Segmento de memoria de video (modo 13h)
		MOV ES, AX
		MOV DI, 0        ; Offset inicial
		MOV AL, 00h      ; Color negro
		MOV CX, 64000    ; 320x200 = 64000 bytes
		CLD              ; Dirección hacia adelante
		REP STOSB        ; Llenar toda la memoria de video

		RET
	CLEAR_SCREEN ENDP

CODE ENDS
END