STACK SEGMENT PARA STACK 	; DEFINICION DEL SEGMENTO DE PILA
	DB 64 DUP(' ') 			; RESERVAR 64 BYTES PARA LA PILA
STACK ENDS 					; FIN DEL SEGMENTO DE PILA

DATA SEGMENT PARA 'DATA' 	; DEFINICION DEL SEGMENTO DE DATOS

	WINDOW_WIDTH  DW 140h 				; EL ANCHO DE LA VENTANA DE 320 PIXELES EN  HEXADECIMAL DADO POR EL VIDEO MODE
	WINDOW_HEIGHT DW 0C8h 				; EL ALTO DE LA VENTANA DE 200 PIXELES EN HEXADECIMAL  DADO POR EL VIDEO MODE
	WINDOW_BOUNDS DW 6					; VARIABLE USADA PARA LAS COLISIONES

	TIME_AUX DB 0 						; VARIABLE USADA PARA VERIFICAR SI EL TIEMPO HA CAMBIADO
	GAME_ACTIVE DB 1 					; INDICA SI EL JUEGO ESTA ACTIVO (1->TRUE 0-> FALSE)
	GAME_STARTED DB 0					; INDICA SI EL JUEGO HA INICIADO (0 -> MENU, 1 -> JUGANDO)
	WINNER_INDEX DB 0					; INDICA EL INDICE DEL GANADOR (1 -> PLAYER_ONE 2 -> PLAYER_TWO)

	BALL_X 			DW 0A0h 			; POSICION EN X (COLUMNA) PARA LA PELOTA
	BALL_Y 			DW 64h 				; POSICION EN Y (FILA) PARA LA PELOTA
	BALL_SIZE 		DW 04h 				; TAMAÑO DE LA PELOTA 4X4 PIXELES 
	BALL_VELOCITY_X DW 05h 				; VELOCIDAD EN X (HORIZONTAL) DE LA PELOTA
	BALL_VELOCITY_Y DW 02h				; VELOCIDAD EN Y (VERTICAL) DE LA PELOTA

	; ===========================================================================
	; [NUEVO] DIFICULTAD PROGRESIVA: VELOCIDADES BASE Y MAXIMAS
	; ===========================================================================
	BALL_BASE_VEL_X DW 05h				; VELOCIDAD BASE EN X (SE RESTAURA AL RESETEAR)
	BALL_BASE_VEL_Y DW 02h				; VELOCIDAD BASE EN Y (SE RESTAURA AL RESETEAR)
	BALL_MAX_VEL_X  DW 0Ch				; VELOCIDAD MAXIMA EN X (12 PIXELES)
	BALL_MAX_VEL_Y  DW 07h				; VELOCIDAD MAXIMA EN Y (7 PIXELES)
	BOUNCE_COUNT    DW 0000h			; CONTADOR DE REBOTES PARA ACELERAR LA PELOTA
	; ===========================================================================

	BALL_ORIGINAL_POS_X DW 0A0h			; POSICION DE LA PELOTA EN X (HORIZONTAL), CENTRO HORIZONTAL DE LA PANTALLA 160 EN HEXADECIMAL 
	BALL_ORIGINAL_POS_Y DW 64h			; POSICION DE LA PELOTA EN Y (VERTICAL), CENTRO VERTICAL DE LA PANTALLA 100 EN HEXADECIMAL

	PADDLE_LEFT_X DW 0Ah				; POSICION ACTUAL DE LA PALETA IZQUIERDA EN X (HORIZONTAL)
	PADDLE_LEFT_Y DW 0Ah				; POSICION ACTUAL DE LA PALETA IZQUIERDA EN Y (VERTICAL)

	PADDLE_RIGHT_X DW 130h				; POSICION ACTUAL DE LA PALETA DERECHA EN X (HORIZONTAL)
	PADDLE_RIGHT_Y DW 0Ah				; POSICION ACTUAL DE LA PALETA DERECHA EN Y (VERTICAL)

	PADDLE_WIDTH 	DW 05h				; ANCHO DE LAS PALETAS
	PADDLE_HEIGHT 	DW 1Fh				; ALTO DE LAS PALETAS
	PADDLE_VELOCITY DW 05h				; VELOCIDAD DE LAS PALETAS

	PLAYER_ONE_POINTS DB 0				; PUNTOS DEL JUGADOR UNO (PALETA IZQUIERDA)
	PLAYER_TWO_POINTS DB 0				; PUNTOS DEL JUGADOR DOS (PALETA DERECHA)

	PLAYER_ONE_POINT_TEXT DB '0', '$'	; TEXTO SOBRE LOS PUNTOS DEL JUGADOR UNO
	PLAYER_TWO_POINT_TEXT DB '0', '$'	; TEXTO SOBRE LOS PUNTOS DEL JUGADOR DOS

	TEXT_GAME_OVER_TITLE DB 'GAME OVER', '$'	    ; TEXTO PARA EL TITULO DE LA PANTALLA DE GAME OVER 
	TEXT_GAME_OVER_WINNER DB 'PLAYER 0 WIN', '$'    ; TEXTO PARA MOSTRAR QUIEN ES EL GANADOR EN LA PANTALLA DE GAME OVER

	; ===========================================================================
	; [NUEVO] TEXTOS PARA LA PANTALLA DE MENU PRINCIPAL
	; ===========================================================================
	TEXT_MENU_TITLE   DB 'PONG', '$'
	TEXT_MENU_P1      DB 'PLAYER 1: W / S', '$'
	TEXT_MENU_P2      DB 'PLAYER 2: UP / DOWN', '$'
	TEXT_MENU_START   DB 'PRESS ENTER TO START', '$'
	TEXT_MENU_WIN     DB 'FIRST TO 5 POINTS WINS', '$'
	; ===========================================================================

	; ===========================================================================
	; [NUEVO] TEXTO PARA PANTALLA DE GAME OVER (REINICIO)
	; ===========================================================================
	TEXT_PLAY_AGAIN   DB 'PRESS ENTER TO PLAY AGAIN', '$'
	TEXT_PRESS_ESC    DB 'PRESS ESC TO EXIT', '$'
	; ===========================================================================

DATA ENDS 					; FIN DEL SEGMENTO DE DATOS

CODE SEGMENT PARA 'CODE' 	; DEFINICION DEL SEGMENTO DE CODIGO

	MAIN PROC FAR 					  ; PROCEDIMIENTO PRINCIPAL DEL PROGRAMA
	ASSUME CS:CODE, DS:DATA, SS:STACK ; ESTABLECER LOS SEGMENTOS A SUS DEBIDOS REGISTROS (CS, DS, SS)
	PUSH DS 						  ; ENVIAR AL STACK EL SEGMENTO DE DATOS (REGISTRO DS)
	SUB AX, AX 						  ; LIMPIAR EL REGISTRO AX
	PUSH AX							  ; ENVIAR EL REGISTRO AX AL STACK
	MOV AX, DATA					  ; GUARDAR EL CONTENIDO DEL DATA SEGMENT EN EL REGISTRO AX
	MOV DS, AX						  ; GUARDAR EN EL REGISTRO DS EL CONTENIDO DEL REGISTRO AX
	POP AX							  ; GUARDAR EL TOP DEL STACK EN EL REGISTRO AX
	POP AX							  ; GUARDAR EL TOP DEL STACK EN EL REGISTRO AX

		MOV AH, 00h  	 ; PONER LA CONFIGURACION HACIA VIDEO MODE
		MOV AL, 13h  	 ; ELEGIR EL MODO DE VIDEO 
		INT 10h      	 ; EJECUTAR INT

        MOV AH, 0Bh  	 ; ELEGIR COLOR DE FONDO
		MOV BH, 00h  	 ; PALETA
        MOV BL, 00h  	 ; ELEGIR COLOR (NEGRO)                   
        INT 10h      	 ; EJECUTAR INT                   

		; =======================================================================
		; [NUEVO] MOSTRAR MENU PRINCIPAL ANTES DE INICIAR EL JUEGO
		; =======================================================================
		SHOW_MENU:
			CALL DRAW_MENU_SCREEN		; DIBUJAR LA PANTALLA DEL MENU

		WAIT_START_KEY:
			MOV AH, 00h				; LEER TECLA PRESIONADA
			INT 16h
			CMP AL, 1Bh				; ESC -> SALIR DEL PROGRAMA
			JE EXIT_PROGRAM
			CMP AL, 0Dh				; ENTER -> INICIAR JUEGO
			JNE WAIT_START_KEY
		; =======================================================================

		; REINICIAR ESTADO DEL JUEGO AL INICIAR/REINICIAR
		CALL RESET_GAME_STATE

		CHECK_TIME: 	 ; ETIQUETA PARA VERIFICAR EL TIEMPO

			CMP GAME_ACTIVE, 00h
			JE SHOW_GAME_OVER

			MOV AH, 2Ch 	 			; OBTENER EL TIEMPO DEL SISTEMA
			INT 21h 	 	 			; CH = HORA, CL = MINUTO, DH = SEGUNDO, DL = 1/100 SEGUNDO
		
			; VERIFICAR SI EL TIEMPO ACTUAL ES IGUAL AL ANTERIOR (TIME_AUX)
			CMP DL, TIME_AUX 
		
			JE CHECK_TIME 	 			; SI ES IGUAL COMPARA OTRA VEZ SINO REALIZAR EL RESTO DE ACCIONES
			MOV TIME_AUX, DL
			
			CALL CLEAR_SCREEN			; LIMPIAR LA PANTALLA PARA EVITAR LA VISUALIZACION DE PIXELES ANTERIORES

			CALL MOVE_BALL				; MOVER LA PELOTA
			CALL DRAW_BALL				; DIBUJAR LA PELOTA

			CALL DRAW_CENTER_LINE		; [NUEVO] DIBUJAR LA LINEA CENTRAL DIVISORIA

			CALL MOVE_PADDLES			; MOVER LAS PALETAS MEDIANTE LOS INPUTS DEL TECLADO
			CALL DRAW_PADDLES			; DIBUJAR LAS PALETAS

			CALL DRAW_UI

			JMP CHECK_TIME 				; LUEGO DE REALIZAR LAS ACCIONES VOLVER A REVISAR EL TIEMPO	

			SHOW_GAME_OVER:
				; =================================================================
				; [NUEVO] PANTALLA DE GAME OVER CON OPCION DE REINICIAR O SALIR
				; =================================================================
				CALL DRAW_GAME_OVER_SCREEN

				; DRAW_GAME_OVER_SCREEN YA ESPERA UNA TECLA
				; AL RETORNAR, AL TIENE LA TECLA PRESIONADA
				CMP AL, 0Dh				; ENTER -> JUGAR DE NUEVO
				JE RESTART_GAME
				CMP AL, 1Bh				; ESC -> SALIR
				JE EXIT_PROGRAM
				JMP SHOW_GAME_OVER		; OTRA TECLA -> ESPERAR DE NUEVO

				RESTART_GAME:
					CALL RESET_GAME_STATE	; REINICIAR VARIABLES DEL JUEGO
					JMP CHECK_TIME			; VOLVER AL LOOP PRINCIPAL
				; =================================================================

		EXIT_PROGRAM:
			; RESTAURAR MODO DE VIDEO A TEXTO ANTES DE SALIR
			MOV AH, 00h
			MOV AL, 03h
			INT 10h
			MOV AH, 4Ch
			INT 21h

		RET 							; RETORNAR AL SISTEMA OPERATIVO
	MAIN ENDP 						    ; FIN DEL PROCEDIMIENTO PRINCIPAL

	; ===========================================================================
	; [NUEVO] PROCEDIMIENTO: DIBUJAR MENU PRINCIPAL
	; Muestra titulo, controles y mensaje de inicio
	; ===========================================================================
	DRAW_MENU_SCREEN PROC NEAR
		CALL CLEAR_SCREEN				; LIMPIAR PANTALLA

		; TITULO "PONG" - CENTRADO
		MOV AH, 02h
		MOV BH, 00h
		MOV DH, 03h					; FILA 3
		MOV DL, 13h					; COLUMNA 19 (CENTRADO EN 40 COLS)
		INT 10h
		MOV AH, 09h
		LEA DX, TEXT_MENU_TITLE
		INT 21h

		; LINEA SEPARADORA DE GUIONES (MANUAL PIXEL A PIXEL CON TEXTO)
		; CONTROLES JUGADOR 1
		MOV AH, 02h
		MOV BH, 00h
		MOV DH, 06h					; FILA 6
		MOV DL, 0Dh					; COLUMNA 13
		INT 10h
		MOV AH, 09h
		LEA DX, TEXT_MENU_P1
		INT 21h

		; CONTROLES JUGADOR 2
		MOV AH, 02h
		MOV BH, 00h
		MOV DH, 08h					; FILA 8
		MOV DL, 0Bh					; COLUMNA 11
		INT 10h
		MOV AH, 09h
		LEA DX, TEXT_MENU_P2
		INT 21h

		; CONDICION DE VICTORIA
		MOV AH, 02h
		MOV BH, 00h
		MOV DH, 0Bh					; FILA 11
		MOV DL, 09h					; COLUMNA 9
		INT 10h
		MOV AH, 09h
		LEA DX, TEXT_MENU_WIN
		INT 21h

		; MENSAJE DE INICIO
		MOV AH, 02h
		MOV BH, 00h
		MOV DH, 0Eh					; FILA 14
		MOV DL, 0Ah					; COLUMNA 10
		INT 10h
		MOV AH, 09h
		LEA DX, TEXT_MENU_START
		INT 21h

		RET
	DRAW_MENU_SCREEN ENDP
	; ===========================================================================

	; ===========================================================================
	; [NUEVO] PROCEDIMIENTO: REINICIAR ESTADO COMPLETO DEL JUEGO
	; Resetea pelota, paletas, puntos y activa el juego
	; ===========================================================================
	RESET_GAME_STATE PROC NEAR
		; RESETEAR PUNTOS
		MOV PLAYER_ONE_POINTS, 00h
		MOV PLAYER_TWO_POINTS, 00h
		CALL UPDATE_TEXT_PLAYER_ONE_POINTS
		CALL UPDATE_TEXT_PLAYER_TWO_POINTS

		; RESETEAR POSICIONES DE PALETAS
		MOV PADDLE_LEFT_Y, 0Ah
		MOV PADDLE_RIGHT_Y, 0Ah

		; RESETEAR PELOTA
		CALL RESET_BALL_POSITION

		; RESETEAR VELOCIDADES DE LA PELOTA A LOS VALORES BASE
		MOV AX, BALL_BASE_VEL_X
		MOV BALL_VELOCITY_X, AX
		MOV AX, BALL_BASE_VEL_Y
		MOV BALL_VELOCITY_Y, AX

		; RESETEAR CONTADOR DE REBOTES
		MOV BOUNCE_COUNT, 0000h

		; RESETEAR INDICE DEL GANADOR
		MOV WINNER_INDEX, 00h

		; ACTIVAR EL JUEGO
		MOV GAME_ACTIVE, 01h

		RET
	RESET_GAME_STATE ENDP
	; ===========================================================================

	; ===========================================================================
	; [NUEVO] PROCEDIMIENTO: DIBUJAR LINEA CENTRAL DIVISORIA (PUNTEADA)
	; Dibuja puntos blancos cada 8 pixeles en X=160 (centro de la pantalla)
	; ===========================================================================
	DRAW_CENTER_LINE PROC NEAR
		MOV DX, 08h					; EMPEZAR DESDE Y=8 (DEJAR BORDE SUPERIOR)
		MOV CX, 0A0h				; X = 160 (CENTRO HORIZONTAL)

		DRAW_CENTER_LOOP:
			; DIBUJAR UN SEGMENTO DE 4 PIXELES DE ALTO
			MOV AH, 0Ch
			MOV AL, 07h				; COLOR GRIS OSCURO (NO TAN BRILLANTE COMO LAS PALETAS)
			MOV BH, 00h
			INT 10h
			INC DX
			MOV AH, 0Ch
			MOV AL, 07h
			MOV BH, 00h
			INT 10h
			INC DX
			MOV AH, 0Ch
			MOV AL, 07h
			MOV BH, 00h
			INT 10h
			INC DX
			MOV AH, 0Ch
			MOV AL, 07h
			MOV BH, 00h
			INT 10h

			ADD DX, 05h				; SALTAR 5 PIXELES (ESPACIO ENTRE SEGMENTOS -> EFECTO PUNTEADO)

			MOV AX, WINDOW_HEIGHT
			SUB AX, 08h				; DEJAR BORDE INFERIOR
			CMP DX, AX
			JL DRAW_CENTER_LOOP		; CONTINUAR SI NO LLEGAMOS AL BORDE

		RET
	DRAW_CENTER_LINE ENDP
	; ===========================================================================

	DRAW_BALL PROC NEAR ; PROCEDIMIENTO PARA DIBUJAR LA PELOTA
		
		MOV CX, BALL_X 				; SELECCIONAR CORDENADA X (COLUMNA) INICIAL
		MOV DX, BALL_Y 				; SELECCIONAR COORDENADA Y (FILA) INICIAL 
	
		DRAW_BALL_LABEL: 			; ETIQUETA PARA DIBUJAR LA PELOTA PIXEL POR PIXEL

			MOV AH, 0Ch 			; DIBUJAR UN PIXEL EN MODO GRAFICO
			MOV AL, 0Fh 			; PONER DE COLOR BLANCO AL PIXEL
			MOV BH, 00h 			; SELECCIONAR PAGINA DE VIDEO
			INT 10h 				; EJECUTAR INT
			INC CX 					; CX = CX + 1
			
			; CX - BALL_X > BALL_SIZE (Y -> IR A LA SIGUIENTE LINEA, N -> SEGUIR A LA SIGUIENTE COLUMNA)
			MOV AX, CX
			SUB AX, BALL_X
			CMP AX, BALL_SIZE
			
			JNG DRAW_BALL_LABEL 	; SALTAR SI NO ES MAYOR 

			MOV CX, BALL_X 			; PONER EL REGISTRO CX EN LA COLUMNA INICIAL
			INC DX					; AVANZAR UNA LINEA
			
			; DX - BALL_Y > BALL_SIZE (Y -> TERMINAR PROCEDIMIENTO, N -> SEGUIR A LA SIGUIENTE LINEA)
			MOV AX, DX
			SUB AX, BALL_Y
			CMP AX, BALL_SIZE
			JNG DRAW_BALL_LABEL

		RET 									; RETORNAR DEL PROCEDIMIENTO
	DRAW_BALL ENDP 								; FIN DEL PROCEDIMIENTO PARA DIBUJAR LA PELOTA

	DRAW_PADDLES PROC NEAR 						; PROCEDIMIENTO PARA DIBUJAR LAS PALETAS
		MOV CX, PADDLE_LEFT_X 					; SELECCIONAR CORDENADA X (COLUMNA) INICIAL
		MOV DX, PADDLE_LEFT_Y 					; SELECCIONAR COORDENADA Y (FILA) INICIAL 

		DRAW_PADDLE_LEFT_HORIZONTAL: 			; ETIQUETA PARA DIBUJAR LA PALETA IZQUIERDA
			MOV AH, 0Ch 						; DIBUJAR UN PIXEL EN MODO GRAFICO
			MOV AL, 0Fh 						; PONER DE COLOR BLANCO AL PIXEL
			MOV BH, 00h 						; SELECCIONAR PAGINA DE VIDEO
			INT 10h 							; EJECUTAR INT
			
			INC CX 								; CX = CX + 1
			; CX - PADDLE_LEFT_X > PADDLE_WIDTH (Y -> IR A LA SIGUIENTE LINEA, N -> SEGUIR A LA SIGUIENTE COLUMNA)
			MOV AX, CX
			SUB AX, PADDLE_LEFT_X
			CMP AX, PADDLE_WIDTH
			
			JNG DRAW_PADDLE_LEFT_HORIZONTAL 	; SALTAR SI NO ES MAYOR 

			MOV CX, PADDLE_LEFT_X 				; PONER EL REGISTRO CX EN LA COLUMNA INICIAL
			INC DX								; AVANZAR UNA LINEA
			
			; DX - PADDLE_LEFT_Y > PADDLE_HEIGHT (Y -> TERMINAR PROCEDIMIENTO, N -> SEGUIR A LA SIGUIENTE LINEA)
			MOV AX, DX
			SUB AX, PADDLE_LEFT_Y
			CMP AX, PADDLE_HEIGHT
			JNG DRAW_PADDLE_LEFT_HORIZONTAL

		MOV CX, PADDLE_RIGHT_X 					; SELECCIONAR CORDENADA X (COLUMNA) INICIAL
		MOV DX, PADDLE_RIGHT_Y 					; SELECCIONAR COORDENADA Y (FILA) INICIAL 

		DRAW_PADDLE_RIGHT_HORIZONTAL: 			; ETIQUETA PARA DIBUJAR LA PALETA DERECHA
			MOV AH, 0Ch 						; DIBUJAR UN PIXEL EN MODO GRAFICO
			MOV AL, 0Fh 						; PONER DE COLOR BLANCO AL PIXEL
			MOV BH, 00h 						; SELECCIONAR PAGINA DE VIDEO
			INT 10h 							; EJECUTAR INT
			
			INC CX 								; CX = CX + 1
			; CX - PADDLE_RIGHT_X > PADDLE_WIDTH (Y -> IR A LA SIGUIENTE LINEA, N -> SEGUIR A LA SIGUIENTE COLUMNA)
			MOV AX, CX
			SUB AX, PADDLE_RIGHT_X
			CMP AX, PADDLE_WIDTH
			
			JNG DRAW_PADDLE_RIGHT_HORIZONTAL 	; SALTAR SI NO ES MAYOR 

			MOV CX, PADDLE_RIGHT_X 				; PONER EL REGISTRO CX EN LA COLUMNA INICIAL
			INC DX								; AVANZAR UNA LINEA
			
			; DX - PADDLE_RIGHT_Y > PADDLE_HEIGHT (Y -> TERMINAR PROCEDIMIENTO, N -> SEGUIR A LA SIGUIENTE LINEA)
			MOV AX, DX
			SUB AX, PADDLE_RIGHT_Y
			CMP AX, PADDLE_HEIGHT
			JNG DRAW_PADDLE_RIGHT_HORIZONTAL

		RET 									; RETORNAR DEL PROCEDIMIENTO
	DRAW_PADDLES ENDP 							; FIN DEL PROCEDIMIENTO PARA DIBUJAR LAS PALETAS

	MOVE_BALL PROC NEAR 						; PROCEDIMIENTO PARA MOVER LA PELOTA

		MOV AX, BALL_VELOCITY_X 		; MOVER LA PELOTA HORIZONTALMENTE
		ADD BALL_X, AX
		
		MOV AX, WINDOW_BOUNDS 
		CMP BALL_X, AX	 				; BALL_X < WINDOW_BOUNDS (Y -> COLISIONO)
		JG CONTINUE_X1
		JMP GIVE_POINT_TO_PLAYER_TWO 	; SUMAR UN PUNTO AL JUGADOR DOS Y RESETAR LA PELOTA			
		CONTINUE_X1:

		MOV AX, WINDOW_WIDTH
		SUB AX, BALL_SIZE
		SUB AX, WINDOW_BOUNDS
		CMP BALL_X, AX					; BALL_X > WINDOW_WIDTH - BALL_SIZE - WINDOW_BOUNDS (Y -> COLISIONO)
		JL CONTINUE_X2
		JMP GIVE_POINT_TO_PLAYER_ONE 	; SUMAR UN PUNTO AL JUGADOR UNO Y RESETAR LA PELOTA
		CONTINUE_X2:

		MOV AX, BALL_VELOCITY_Y			; MOVER LA PELOTA VERTICALMENTE
		ADD BALL_Y, AX
		
		MOV AX, WINDOW_BOUNDS
		CMP BALL_Y, AX					; BALL_Y < WINDOW_BOUNDS (Y -> COLISIONO)
		JG CONTINUE_Y1
		JMP NEG_VELOCITY_Y
		CONTINUE_Y1:

		MOV AX, WINDOW_HEIGHT
		SUB AX, BALL_SIZE
		SUB AX, WINDOW_BOUNDS
		CMP BALL_Y, AX
		JL CONTINUE_Y2					; BALL_Y > WINDOW_HEIGHT - BALL_SIZE - WINDOW_BOUNDS (Y -> COLISIONO)
		JMP NEG_VELOCITY_Y
		CONTINUE_Y2:

		; VERIFICAR COLISION CON PALETA DERECHA
		MOV AX, BALL_X
		ADD AX, BALL_SIZE
		CMP AX, PADDLE_RIGHT_X
		JNG CHECK_COLLISION_WITH_PADDLE_LEFT
		
		MOV AX, PADDLE_RIGHT_X
		ADD AX, PADDLE_WIDTH
		CMP BALL_X, AX
		JNL CHECK_COLLISION_WITH_PADDLE_LEFT

		MOV AX, BALL_Y
		ADD AX, BALL_SIZE
		CMP AX, PADDLE_RIGHT_Y
		JNG CHECK_COLLISION_WITH_PADDLE_LEFT

		MOV AX, PADDLE_RIGHT_Y
		ADD AX, PADDLE_HEIGHT
		CMP BALL_Y, AX
		JNL CHECK_COLLISION_WITH_PADDLE_LEFT

		; COLISION CON PALETA DERECHA CONFIRMADA
		NEG BALL_VELOCITY_X
		; ===================================================================
		; [NUEVO] DIFICULTAD PROGRESIVA: INCREMENTAR VELOCIDAD AL REBOTAR
		; ===================================================================
		CALL INCREASE_BALL_SPEED
		CALL BEEP_PADDLE					; [NUEVO] SONIDO DE REBOTE EN PALETA
		; ===================================================================
		RET

		CHECK_COLLISION_WITH_PADDLE_LEFT:
				MOV AX, BALL_X
				ADD AX, BALL_SIZE
				CMP AX, PADDLE_LEFT_X
				JNG MOVE_BALL_EXIT
				
				MOV AX, PADDLE_LEFT_X
				ADD AX, PADDLE_WIDTH
				CMP BALL_X, AX
				JNL MOVE_BALL_EXIT

				MOV AX, BALL_Y
				ADD AX, BALL_SIZE
				CMP AX, PADDLE_LEFT_Y
				JNG MOVE_BALL_EXIT

				MOV AX, PADDLE_LEFT_Y
				ADD AX, PADDLE_HEIGHT
				CMP BALL_Y, AX
				JNL MOVE_BALL_EXIT

			; COLISION CON PALETA IZQUIERDA CONFIRMADA
			NEG BALL_VELOCITY_X
			; ===============================================================
			; [NUEVO] DIFICULTAD PROGRESIVA: INCREMENTAR VELOCIDAD AL REBOTAR
			; ===============================================================
			CALL INCREASE_BALL_SPEED
			CALL BEEP_PADDLE				; [NUEVO] SONIDO DE REBOTE EN PALETA
			; ===============================================================

		MOVE_BALL_EXIT:
			RET 						; RETORNAR DEL PROCEDIMIENTO

		GIVE_POINT_TO_PLAYER_ONE: 		; ETIQUETA PARA RESETEAR LA POSICION DE LA PELOTA Y AÑADIR UN PUNTO AL JUGADOR UNO
			INC PLAYER_ONE_POINTS
			CALL RESET_BALL_POSITION
			CALL RESET_BALL_SPEED		; [NUEVO] RESETEAR VELOCIDAD AL MARCAR PUNTO
			CALL BEEP_SCORE				; [NUEVO] SONIDO DE PUNTO ANOTADO
			CALL UPDATE_TEXT_PLAYER_ONE_POINTS
			CMP PLAYER_ONE_POINTS, 05h
			JGE GAME_OVER
			RET 						; RETORNAR DESPUES DE RESETEAR POSICION
		
		GIVE_POINT_TO_PLAYER_TWO:
			INC PLAYER_TWO_POINTS
			CALL RESET_BALL_POSITION
			CALL RESET_BALL_SPEED		; [NUEVO] RESETEAR VELOCIDAD AL MARCAR PUNTO
			CALL BEEP_SCORE				; [NUEVO] SONIDO DE PUNTO ANOTADO
			CALL UPDATE_TEXT_PLAYER_TWO_POINTS
			CMP PLAYER_TWO_POINTS, 05h
			JGE GAME_OVER
			RET 						; RETORNAR DESPUES DE RESETEAR POSICION
		
		NEG_VELOCITY_Y: 				; ETIQUETA PARA INVERTIR LA VELOCIDAD EN Y
			NEG BALL_VELOCITY_Y
			CALL BEEP_WALL				; [NUEVO] SONIDO DE REBOTE EN PARED
			RET 						; RETORNAR DESPUES DE INVERTIR VELOCIDAD

		GAME_OVER:						; LLAMAR CUANDO SE HALLAN COMPLETADO LOS 5 PUNTOS
			CMP PLAYER_ONE_POINTS, 05h
			JNL WINNER_IS_PLAYER_ONE
			JMP WINNER_IS_PLAYER_TWO

			WINNER_IS_PLAYER_ONE:
				MOV WINNER_INDEX, 01h
				JMP CONTINUE_GAME_OVER

			WINNER_IS_PLAYER_TWO:
				MOV WINNER_INDEX, 02h
				JMP CONTINUE_GAME_OVER
			
			CONTINUE_GAME_OVER:
			MOV GAME_ACTIVE, 00h
			RET


	MOVE_BALL ENDP 						; FIN DEL PROCEDIMIENTO PARA MOVER LA PELOTA

	; ===========================================================================
	; [NUEVO] PROCEDIMIENTO: AUMENTAR VELOCIDAD DE LA PELOTA (DIFICULTAD PROGRESIVA)
	; Cada 3 rebotes se incrementa la velocidad en X e Y respetando el maximo
	; ===========================================================================
	INCREASE_BALL_SPEED PROC NEAR
		INC BOUNCE_COUNT

		; SOLO AUMENTAR CADA 3 REBOTES
		MOV AX, BOUNCE_COUNT
		MOV BX, 0003h
		XOR DX, DX
		DIV BX
		CMP DX, 0000h
		JNE SPEED_EXIT					; SI NO ES MULTIPLO DE 3, NO AUMENTAR

		; AUMENTAR VELOCIDAD EN X (MANTENIENDO EL SIGNO)
		MOV AX, BALL_VELOCITY_X
		OR AX, AX
		JNS INC_VEL_X_POSITIVE			; SI ES POSITIVO SALTAR

		; VELOCIDAD X NEGATIVA: DECREMENTAR (HACER MAS NEGATIVA)
		CMP AX, -0Ch					; COMPARAR CON MAXIMO NEGATIVO (-12)
		JLE SKIP_INC_X					; SI YA LLEGO AL MAXIMO NEGATIVO, NO AUMENTAR
		DEC AX
		MOV BALL_VELOCITY_X, AX
		JMP CHECK_VEL_Y

		INC_VEL_X_POSITIVE:
			; VELOCIDAD X POSITIVA
			MOV BX, BALL_MAX_VEL_X
			CMP AX, BX
			JGE SKIP_INC_X				; SI YA LLEGO AL MAXIMO, NO AUMENTAR
			INC AX
			MOV BALL_VELOCITY_X, AX

		SKIP_INC_X:

		CHECK_VEL_Y:
		; AUMENTAR VELOCIDAD EN Y (MANTENIENDO EL SIGNO)
		MOV AX, BALL_VELOCITY_Y
		OR AX, AX
		JNS INC_VEL_Y_POSITIVE

		; VELOCIDAD Y NEGATIVA
		CMP AX, -07h					; MAXIMO NEGATIVO EN Y (-7)
		JLE SPEED_EXIT
		DEC AX
		MOV BALL_VELOCITY_Y, AX
		JMP SPEED_EXIT

		INC_VEL_Y_POSITIVE:
			MOV BX, BALL_MAX_VEL_Y
			CMP AX, BX
			JGE SPEED_EXIT
			INC AX
			MOV BALL_VELOCITY_Y, AX

		SPEED_EXIT:
			RET
	INCREASE_BALL_SPEED ENDP
	; ===========================================================================

	; ===========================================================================
	; [NUEVO] PROCEDIMIENTO: RESETEAR VELOCIDAD DE LA PELOTA A VALORES BASE
	; Se llama al marcar un punto para reiniciar la dificultad
	; ===========================================================================
	RESET_BALL_SPEED PROC NEAR
		; RESTAURAR VELOCIDADES BASE (PRESERVAR SIGNO ACTUAL DE X E Y)
		MOV AX, BALL_VELOCITY_X
		OR AX, AX
		JNS RESET_VEL_X_POS

		; VELOCIDAD X ERA NEGATIVA -> RESTAURAR BASE NEGATIVA
		MOV AX, BALL_BASE_VEL_X
		NEG AX
		MOV BALL_VELOCITY_X, AX
		JMP CHECK_RESET_Y

		RESET_VEL_X_POS:
			MOV AX, BALL_BASE_VEL_X
			MOV BALL_VELOCITY_X, AX

		CHECK_RESET_Y:
		MOV AX, BALL_VELOCITY_Y
		OR AX, AX
		JNS RESET_VEL_Y_POS

		MOV AX, BALL_BASE_VEL_Y
		NEG AX
		MOV BALL_VELOCITY_Y, AX
		JMP RESET_SPEED_EXIT

		RESET_VEL_Y_POS:
			MOV AX, BALL_BASE_VEL_Y
			MOV BALL_VELOCITY_Y, AX

		RESET_SPEED_EXIT:
			MOV BOUNCE_COUNT, 0000h		; REINICIAR CONTADOR DE REBOTES
			RET
	RESET_BALL_SPEED ENDP
	; ===========================================================================

	; ===========================================================================
	; [NUEVO] PROCEDIMIENTO: BEEP AL REBOTAR EN UNA PALETA
	; Tono mas agudo para indicar colision con paleta
	; Usa el altavoz del PC via puertos 42h/43h/61h
	; ===========================================================================
	BEEP_PADDLE PROC NEAR
		; FRECUENCIA ~800 Hz: DIVISOR = 1193180 / 800 = 1491 = 05D3h
		MOV AL, 0B6h				; CONFIGURAR TIMER 2: MODO 3 (CUADRADA), CANAL 2
		OUT 43h, AL
		MOV AX, 05D3h				; DIVISOR PARA ~800 Hz
		OUT 42h, AL				; BYTE BAJO
		MOV AL, AH
		OUT 42h, AL				; BYTE ALTO

		IN AL, 61h				; LEER PUERTO DEL ALTAVOZ
		OR AL, 03h				; ACTIVAR BITS 0 Y 1 (ENCENDER ALTAVOZ)
		OUT 61h, AL

		; DURACION CORTA: LOOP DE ESPERA ~15ms
		MOV CX, 0C000h
		BEEP_P_WAIT: LOOP BEEP_P_WAIT

		IN AL, 61h
		AND AL, 0FCh				; DESACTIVAR BITS 0 Y 1 (APAGAR ALTAVOZ)
		OUT 61h, AL
		RET
	BEEP_PADDLE ENDP
	; ===========================================================================

	; ===========================================================================
	; [NUEVO] PROCEDIMIENTO: BEEP AL REBOTAR EN UNA PARED (TECHO/SUELO)
	; Tono mas grave que el de paleta
	; ===========================================================================
	BEEP_WALL PROC NEAR
		; FRECUENCIA ~400 Hz: DIVISOR = 1193180 / 400 = 2982 = 0BA6h
		MOV AL, 0B6h
		OUT 43h, AL
		MOV AX, 0BA6h				; DIVISOR PARA ~400 Hz
		OUT 42h, AL
		MOV AL, AH
		OUT 42h, AL

		IN AL, 61h
		OR AL, 03h
		OUT 61h, AL

		MOV CX, 08000h
		BEEP_W_WAIT: LOOP BEEP_W_WAIT

		IN AL, 61h
		AND AL, 0FCh
		OUT 61h, AL
		RET
	BEEP_WALL ENDP
	; ===========================================================================

	; ===========================================================================
	; [NUEVO] PROCEDIMIENTO: BEEP AL ANOTAR UN PUNTO
	; Secuencia de dos tonos ascendentes para celebrar el punto
	; ===========================================================================
	BEEP_SCORE PROC NEAR
		; PRIMER TONO: ~600 Hz
		MOV AL, 0B6h
		OUT 43h, AL
		MOV AX, 07D0h				; DIVISOR PARA ~600 Hz
		OUT 42h, AL
		MOV AL, AH
		OUT 42h, AL

		IN AL, 61h
		OR AL, 03h
		OUT 61h, AL

		MOV CX, 0FFFFh
		BEEP_S1_WAIT: LOOP BEEP_S1_WAIT

		IN AL, 61h
		AND AL, 0FCh
		OUT 61h, AL

		; BREVE SILENCIO
		MOV CX, 4000h
		BEEP_S_SIL: LOOP BEEP_S_SIL

		; SEGUNDO TONO: ~1000 Hz (MAS AGUDO)
		MOV AL, 0B6h
		OUT 43h, AL
		MOV AX, 04B0h				; DIVISOR PARA ~1000 Hz
		OUT 42h, AL
		MOV AL, AH
		OUT 42h, AL

		IN AL, 61h
		OR AL, 03h
		OUT 61h, AL

		MOV CX, 0FFFFh
		BEEP_S2_WAIT: LOOP BEEP_S2_WAIT

		IN AL, 61h
		AND AL, 0FCh
		OUT 61h, AL
		RET
	BEEP_SCORE ENDP
	; ===========================================================================

	MOVE_PADDLES PROC NEAR 				; PROCEDIMIENTO PARA MOVER LAS PALETAS
		MOV AH, 01h							
		INT 16h
		JZ CHECK_RIGHT_PADDLE_MOVEMENT		; ZF = 1 NO HAY TECLA PRECIONADA

		MOV AH, 00h							; REVISAR QUE TECLA ESTA SIENDO PRECIONADA
		INT 16h

		; SI ES "W" o "w" MOVER HACIA ARRIBA 
		CMP AL, 77h  						; "w"
		JE MOVE_LEFT_PADDLE_UP					
		CMP AL, 57h  						; "W"
		JE MOVE_LEFT_PADDLE_UP					
		
		; SI ES "S" o "s" MOVER HACIA ABAJO
		CMP AL, 73h  						; "s"
		JE MOVE_LEFT_PADDLE_DOWN					
		CMP AL, 53h  						; "S"
		JE MOVE_LEFT_PADDLE_DOWN					
		
		JMP CHECK_RIGHT_PADDLE_MOVEMENT
		
		MOVE_LEFT_PADDLE_UP:
			MOV AX, PADDLE_VELOCITY
			SUB PADDLE_LEFT_Y, AX
			
			MOV AX, WINDOW_BOUNDS
			CMP PADDLE_LEFT_Y, AX
			JL FIX_PADDLE_LEFT_TOP_POSITION
			JMP CHECK_RIGHT_PADDLE_MOVEMENT

			FIX_PADDLE_LEFT_TOP_POSITION:
				MOV AX, WINDOW_BOUNDS
				MOV PADDLE_LEFT_Y, AX
				JMP CHECK_RIGHT_PADDLE_MOVEMENT
		

		MOVE_LEFT_PADDLE_DOWN:
			MOV AX, PADDLE_VELOCITY
			ADD PADDLE_LEFT_Y, AX

			MOV AX, WINDOW_HEIGHT
			SUB AX, WINDOW_BOUNDS
			SUB AX, PADDLE_HEIGHT
			CMP PADDLE_LEFT_Y, AX
			JG FIX_PADDLE_LEFT_BOTTOM_POSITION
			JMP CHECK_RIGHT_PADDLE_MOVEMENT

			FIX_PADDLE_LEFT_BOTTOM_POSITION:
				MOV PADDLE_LEFT_Y, AX
				JMP CHECK_RIGHT_PADDLE_MOVEMENT

		CHECK_RIGHT_PADDLE_MOVEMENT:
			CMP AH, 48h  						; FLECHA ARRIBA
			JE MOVE_RIGHT_PADDLE_UP					
			
			CMP AH, 50h  						; FLECHA ABAJO
			JE MOVE_RIGHT_PADDLE_DOWN				
			JMP EXIT_PADDLE_MOVEMENT

			MOVE_RIGHT_PADDLE_UP:
				MOV AX, PADDLE_VELOCITY
				SUB PADDLE_RIGHT_Y, AX
				
				MOV AX, WINDOW_BOUNDS
				CMP PADDLE_RIGHT_Y, AX
				JL FIX_PADDLE_RIGHT_TOP_POSITION
				JMP EXIT_PADDLE_MOVEMENT

				FIX_PADDLE_RIGHT_TOP_POSITION:
					MOV AX, WINDOW_BOUNDS
					MOV PADDLE_RIGHT_Y, AX
					JMP EXIT_PADDLE_MOVEMENT

			MOVE_RIGHT_PADDLE_DOWN:
				MOV AX, PADDLE_VELOCITY
				ADD PADDLE_RIGHT_Y, AX

				MOV AX, WINDOW_HEIGHT
				SUB AX, WINDOW_BOUNDS
				SUB AX, PADDLE_HEIGHT
				CMP PADDLE_RIGHT_Y, AX
				JG FIX_PADDLE_RIGHT_BOTTOM_POSITION
				JMP EXIT_PADDLE_MOVEMENT

				FIX_PADDLE_RIGHT_BOTTOM_POSITION:
					MOV PADDLE_RIGHT_Y, AX
					JMP EXIT_PADDLE_MOVEMENT

		EXIT_PADDLE_MOVEMENT:
			RET
	MOVE_PADDLES ENDP

	RESET_BALL_POSITION PROC NEAR

		MOV AX, BALL_ORIGINAL_POS_X
		MOV BALL_X, AX

		MOV AX, BALL_ORIGINAL_POS_Y
		MOV BALL_Y, AX

		RET
	RESET_BALL_POSITION ENDP

	DRAW_UI PROC NEAR

	; DIBUJAR LOS PUNTOS DEL JUGADOR UNO 
	MOV AH, 02h
	MOV BH, 00h
	MOV DH, 04h
	MOV DL, 06h
	INT 10h	

	MOV AH, 09h
	LEA DX, PLAYER_ONE_POINT_TEXT
	INT 21h

	; DIBUJAR LOS PUNTOS DEL JUGADOR DOS
	MOV AH, 02h
	MOV BH, 00h
	MOV DH, 04h
	MOV DL, 20h
	INT 10h	

	MOV AH, 09h
	LEA DX, PLAYER_TWO_POINT_TEXT
	INT 21h

	RET
	DRAW_UI ENDP

	UPDATE_TEXT_PLAYER_ONE_POINTS PROC NEAR
		XOR AX,AX
		MOV AL, PLAYER_ONE_POINTS
		ADD AL, 30h
		MOV [PLAYER_ONE_POINT_TEXT], AL
		RET
	UPDATE_TEXT_PLAYER_ONE_POINTS ENDP

	UPDATE_TEXT_PLAYER_TWO_POINTS PROC NEAR
		XOR AX,AX
		MOV AL, PLAYER_TWO_POINTS
		ADD AL, 30h
		MOV [PLAYER_TWO_POINT_TEXT], AL
		RET
	UPDATE_TEXT_PLAYER_TWO_POINTS ENDP

	; ===========================================================================
	; PROCEDIMIENTO: DIBUJAR PANTALLA DE GAME OVER (MODIFICADO)
	; Ahora muestra opciones de reiniciar o salir y retorna AL con la tecla elegida
	; ===========================================================================
	DRAW_GAME_OVER_SCREEN PROC NEAR
		
		CALL CLEAR_SCREEN
		; MOSTRAR EL TITULO DEL MENU
		MOV AH, 02h
		MOV BH, 00h
		MOV DH, 04h
		MOV DL, 04h
		INT 10h	

		MOV AH, 09h
		LEA DX, TEXT_GAME_OVER_TITLE
		INT 21h

		; MOSTRAR EL GANADOR
		MOV AH, 02h
		MOV BH, 00h
		MOV DH, 06h
		MOV DL, 04h
		INT 10h	

		CALL UPDATE_WINNER_TEXT

		MOV AH, 09h
		LEA DX, TEXT_GAME_OVER_WINNER
		INT 21h

		; =======================================================================
		; [NUEVO] MOSTRAR OPCIONES: JUGAR DE NUEVO O SALIR
		; =======================================================================
		MOV AH, 02h
		MOV BH, 00h
		MOV DH, 09h					; FILA 9
		MOV DL, 04h
		INT 10h
		MOV AH, 09h
		LEA DX, TEXT_PLAY_AGAIN
		INT 21h

		MOV AH, 02h
		MOV BH, 00h
		MOV DH, 0Bh					; FILA 11
		MOV DL, 04h
		INT 10h
		MOV AH, 09h
		LEA DX, TEXT_PRESS_ESC
		INT 21h
		; =======================================================================

		; ESPERAR UNA PULSACION Y RETORNARLA EN AL
		MOV AH, 00h
		INT 16h						; AL = CARACTER ASCII DE LA TECLA

		RET
	DRAW_GAME_OVER_SCREEN ENDP
	; ===========================================================================

	UPDATE_WINNER_TEXT PROC NEAR
		MOV AL, WINNER_INDEX
		ADD AL, 30h
		MOV [TEXT_GAME_OVER_WINNER + 7], AL
		RET
	UPDATE_WINNER_TEXT ENDP

	CLEAR_SCREEN PROC NEAR
		MOV AX, 0A000h
		MOV ES, AX
		MOV DI, 0
		MOV AL, 00h
		MOV CX, 64000
		CLD
		REP STOSB
		RET
	CLEAR_SCREEN ENDP

CODE ENDS
END
